name: Discourse News
on:
  schedule: [{cron: "15 1 * * *"}]
  workflow_dispatch:
jobs:
  discourse-news-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Discourse News
        run: |
          mkdir -p news
          curl --fail --location --retry 3 --user-agent "Mozilla/5.0" \
            "https://universal-blue.discourse.group/embed/topics?discourse_embed_id=de-8yypuu3ls&per_page=5&tags=bazzite-news&template=complete" \
            --output news/index.html
          sed -i -E 's#(href|src|srcset)=(['\''"])/#\1=\2https://universal-blue.discourse.group/#g' news/index.html
        working-directory: ${{ github.workspace }}

      - name: Write Discourse News to Repository
        uses: test-room-7/action-update-file@6b8249d09d5926fbae288c0bb640757f09ec7ce0 # v2
        with:
          file-path: news/index.html
          commit-msg: Discourse News Update
          github-token: ${{ secrets.GITHUB_TOKEN }}